spring.application.name=erp-saas

spring.datasource.url=jdbc:mysql://localhost:3306/erp_saas
spring.datasource.username=root
spring.datasource.password=Vidhi@23

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true


